#!/usr/bin/env bash

set -euo pipefail

# Deployment settings. Update these values for the target Home Assistant host.
HOME_ASSISTANT_SSH="sato@192.168.1.35"
FIRMWARE_SERVER_URL="https://192.168.1.35:8443/greensync/ota"
REMOTE_CA_CERT="/opt/greensync/firmware-server/certs/ca.crt"
DEFAULT_HARDWARE_ID="m5stack-atoms3-lite"
DEFAULT_CHANNEL="stable"

usage() {
  cat <<'EOF'
Usage:
  upload-firmware-to-homeassistant.sh --version VERSION --firmware FILE [options]

Required:
  --version VERSION   Release version, for example 0.3.1
  --firmware FILE     Application image generated by PlatformIO

Options:
  --hardware ID       Hardware ID (default: m5stack-atoms3-lite)
  --channel CHANNEL   Release channel (default: stable)
  -h, --help          Show this help

Connection settings are configured at the top of this script.
EOF
}

require_value() {
  local option="$1"
  local value="${2:-}"
  if [[ -z "$value" ]]; then
    echo "Error: $option requires a value" >&2
    exit 1
  fi
}

version=""
firmware_file=""
hardware_id="$DEFAULT_HARDWARE_ID"
channel="$DEFAULT_CHANNEL"

while (( $# > 0 )); do
  case "$1" in
    --version)
      require_value "$1" "${2:-}"
      version="$2"
      shift 2
      ;;
    --firmware)
      require_value "$1" "${2:-}"
      firmware_file="$2"
      shift 2
      ;;
    --hardware)
      require_value "$1" "${2:-}"
      hardware_id="$2"
      shift 2
      ;;
    --channel)
      require_value "$1" "${2:-}"
      channel="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

[[ -n "$version" ]] || { echo "Error: --version is required" >&2; exit 1; }
[[ -n "$firmware_file" ]] || { echo "Error: --firmware is required" >&2; exit 1; }

script_dir="$(cd "$(dirname "$0")" && pwd)"
repository_dir="$(cd "$script_dir/.." && pwd)"
publisher="$script_dir/publish-firmware.sh"
if [[ "$firmware_file" = /* ]]; then
  firmware_path="$firmware_file"
else
  firmware_path="$repository_dir/$firmware_file"
fi
firmware_directory="$(dirname "$firmware_path")"
firmware_pattern="$(basename "$firmware_path")"
temporary_directory="$(mktemp -d)"
ca_certificate="$temporary_directory/server.crt"

cleanup() {
  rm -rf "$temporary_directory"
}
trap cleanup EXIT

for command in scp curl python3; do
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "Error: required command is unavailable: $command" >&2
    exit 1
  fi
done

if [[ ! -x "$publisher" ]]; then
  echo "Error: publisher is not executable: $publisher" >&2
  exit 1
fi

if [[ ! -f "$firmware_path" ]]; then
  echo "Error: firmware file does not exist: $firmware_path" >&2
  echo "Build it first with: (cd firmware/atom-s3-lite && pio run)" >&2
  exit 1
fi

echo "Fetching Firmware Server CA certificate..."
scp "$HOME_ASSISTANT_SSH:$REMOTE_CA_CERT" "$ca_certificate"

release_manifest="$temporary_directory/release-manifest.json"
release_url="${FIRMWARE_SERVER_URL%/}/api/v1/releases/$hardware_id/$version/manifest.json"
http_status="$(curl \
  --silent \
  --show-error \
  --cacert "$ca_certificate" \
  --output "$release_manifest" \
  --write-out '%{http_code}' \
  "$release_url")"

skip_publish=false
if [[ "$http_status" == "200" ]]; then
  if python3 - "$release_manifest" "$firmware_path" "$hardware_id" "$version" <<'PY'
import hashlib
import json
import pathlib
import sys

manifest_path, firmware_path, hardware, version = sys.argv[1:]
manifest = json.loads(pathlib.Path(manifest_path).read_text())
firmware = pathlib.Path(firmware_path).read_bytes()
expected = {
    "hardware": hardware,
    "version": version,
    "size": len(firmware),
    "sha256": hashlib.sha256(firmware).hexdigest(),
}
mismatches = [
    f"{key}: server={manifest.get(key)!r}, local={value!r}"
    for key, value in expected.items()
    if manifest.get(key) != value
]
if mismatches:
    print("Error: the immutable release exists with different content:", file=sys.stderr)
    for mismatch in mismatches:
        print(f"  {mismatch}", file=sys.stderr)
    print("Use a new version for the changed binary.", file=sys.stderr)
    raise SystemExit(1)
PY
  then
    echo "Release $version already exists with the same size and SHA-256; skipping upload."
    skip_publish=true
  else
    exit 1
  fi
elif [[ "$http_status" != "404" ]]; then
  echo "Error: release lookup returned HTTP $http_status" >&2
  cat "$release_manifest" >&2
  exit 1
fi

if [[ "$skip_publish" == false && -z "${GREENSYNC_FIRMWARE_SERVER_TOKEN:-}" ]]; then
  echo
  echo "On the Home Assistant server, obtain the token with:"
  echo "  sudo cat /opt/greensync/firmware-server/secrets/deployment-token.txt"
  echo "Then paste it below. Input is not echoed or stored by this script."
  read -r -s -p "Deployment token: " GREENSYNC_FIRMWARE_SERVER_TOKEN
  echo
fi

if [[ "$skip_publish" == false && -z "$GREENSYNC_FIRMWARE_SERVER_TOKEN" ]]; then
  echo "Error: deployment token must not be empty" >&2
  exit 1
fi

export GREENSYNC_FIRMWARE_SERVER_URL="$FIRMWARE_SERVER_URL"
export GREENSYNC_FIRMWARE_SERVER_TOKEN
export GREENSYNC_FIRMWARE_CA_CERT="$ca_certificate"

if [[ "$skip_publish" == false ]]; then
  echo "Publishing firmware..."
  "$publisher" \
    "$firmware_directory" \
    --pattern "$firmware_pattern" \
    --version "$version" \
    --hardware "$hardware_id" \
    --channel "$channel"
fi

manifest_url="${FIRMWARE_SERVER_URL%/}/api/v1/channels/$hardware_id/$channel/manifest.json"
echo
echo "Published manifest:"
curl \
  --fail-with-body \
  --silent \
  --show-error \
  --cacert "$ca_certificate" \
  "$manifest_url"
echo
echo "Firmware upload completed."
