#!/usr/bin/env bash

set -euo pipefail

# Deployment settings. Update these values for the target Home Assistant host.
HOME_ASSISTANT_SSH="sato@192.168.1.35"
FIRMWARE_SERVER_URL="https://192.168.1.35:8443/greensync/ota"
REMOTE_CA_CERT="/opt/greensync/firmware-server/certs/server.crt"
DEFAULT_HARDWARE_ID="m5stack-atoms3-lite"
DEFAULT_CHANNEL="stable"

usage() {
  cat <<'EOF'
Usage:
  upload-firmware-to-homeassistant.sh --version VERSION --firmware FILE [options]

Required:
  --version VERSION   Release version, for example 0.3.1
  --firmware FILE     Application image generated by PlatformIO

Options:
  --hardware ID       Hardware ID (default: m5stack-atoms3-lite)
  --channel CHANNEL   Release channel (default: stable)
  -h, --help          Show this help

Connection settings are configured at the top of this script.
EOF
}

require_value() {
  local option="$1"
  local value="${2:-}"
  if [[ -z "$value" ]]; then
    echo "Error: $option requires a value" >&2
    exit 1
  fi
}

version=""
firmware_file=""
hardware_id="$DEFAULT_HARDWARE_ID"
channel="$DEFAULT_CHANNEL"

while (( $# > 0 )); do
  case "$1" in
    --version)
      require_value "$1" "${2:-}"
      version="$2"
      shift 2
      ;;
    --firmware)
      require_value "$1" "${2:-}"
      firmware_file="$2"
      shift 2
      ;;
    --hardware)
      require_value "$1" "${2:-}"
      hardware_id="$2"
      shift 2
      ;;
    --channel)
      require_value "$1" "${2:-}"
      channel="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

[[ -n "$version" ]] || { echo "Error: --version is required" >&2; exit 1; }
[[ -n "$firmware_file" ]] || { echo "Error: --firmware is required" >&2; exit 1; }

script_dir="$(cd "$(dirname "$0")" && pwd)"
repository_dir="$(cd "$script_dir/.." && pwd)"
publisher="$script_dir/publish-firmware.sh"
if [[ "$firmware_file" = /* ]]; then
  firmware_path="$firmware_file"
else
  firmware_path="$repository_dir/$firmware_file"
fi
firmware_directory="$(dirname "$firmware_path")"
firmware_pattern="$(basename "$firmware_path")"
temporary_directory="$(mktemp -d)"
ca_certificate="$temporary_directory/server.crt"

cleanup() {
  rm -rf "$temporary_directory"
}
trap cleanup EXIT

for command in scp curl; do
  if ! command -v "$command" >/dev/null 2>&1; then
    echo "Error: required command is unavailable: $command" >&2
    exit 1
  fi
done

if [[ ! -x "$publisher" ]]; then
  echo "Error: publisher is not executable: $publisher" >&2
  exit 1
fi

if [[ ! -f "$firmware_path" ]]; then
  echo "Error: firmware file does not exist: $firmware_path" >&2
  echo "Build it first with: (cd firmware/atom-s3-lite && pio run)" >&2
  exit 1
fi

echo "Fetching Firmware Server CA certificate..."
scp "$HOME_ASSISTANT_SSH:$REMOTE_CA_CERT" "$ca_certificate"

if [[ -z "${GREENSYNC_FIRMWARE_SERVER_TOKEN:-}" ]]; then
  echo
  echo "On the Home Assistant server, obtain the token with:"
  echo "  sudo cat /opt/greensync/firmware-server/secrets/deployment-token.txt"
  echo "Then paste it below. Input is not echoed or stored by this script."
  read -r -s -p "Deployment token: " GREENSYNC_FIRMWARE_SERVER_TOKEN
  echo
fi

if [[ -z "$GREENSYNC_FIRMWARE_SERVER_TOKEN" ]]; then
  echo "Error: deployment token must not be empty" >&2
  exit 1
fi

export GREENSYNC_FIRMWARE_SERVER_URL="$FIRMWARE_SERVER_URL"
export GREENSYNC_FIRMWARE_SERVER_TOKEN
export GREENSYNC_FIRMWARE_CA_CERT="$ca_certificate"

echo "Publishing firmware..."
"$publisher" \
  "$firmware_directory" \
  --pattern "$firmware_pattern" \
  --version "$version" \
  --hardware "$hardware_id" \
  --channel "$channel"

manifest_url="${FIRMWARE_SERVER_URL%/}/api/v1/channels/$hardware_id/$channel/manifest.json"
echo
echo "Published manifest:"
curl \
  --fail-with-body \
  --silent \
  --show-error \
  --cacert "$ca_certificate" \
  "$manifest_url"
echo
echo "Firmware upload completed."
